### ISSUE TITLE
Announcement of Soundness score?

### ISSUE THREAD

**Issue by nschneid** [acl-org/aclrollingreview#102]
https://aclrollingreview.org/reviewform does not mention a Soundness score, but I see it is in the review form for the October cycle. Should it be added and explained in a blog post?

Also, will there be any changes to the metareview form?

**Comment by jkkummerfeld** [comment]
Thanks for pointing this out. I have added it to the website.

Re: blog post, the review deadline just passed, so it doesn't make sense now. I'll suggest it for when the next review cycle starts.

Re: metareview - no, this will stay the same (the question was added to the review form after discussion between the EICs and the PCs and they decided not to add it to the meta-reviews).
