### ISSUE TITLE
commitment.json not formatted for API 2

### ISSUE THREAD

**Issue by ipavlopoulos** [acl-org/aclrollingreview#124]
**Bug description:** The JSON format of the current [commitment file](https://aclrollingreview.org/commitments.json) provided by the [ARR website](https://aclrollingreview.org/) is not formatted for API 2, employed by all commitment venues.

**Suggested fix**: In collaboration with the OpenReview team, I created a PR with the suggested revision.

**Comment by jkkummerfeld** [comment]
Merged - thanks for raising and resolving this!
