### ISSUE TITLE
Clarifications regarding reviewer discussion

### ISSUE THREAD

**Issue by neubig** [acl-org/aclrollingreview#14]
Questions from @nschneid:

* Is it recommended to always open the floor for discussion, or just when there is disagreement among reviews?
* Are there things AEs should be on the lookout for that would be inappropriate in reviews, and ask the reviewers to edit? E.g. vague criticisms (ask the reviewer to be more concrete), overly harsh tone....

**Comment by jkkummerfeld** [comment]
Adding these to the draft new page with guidance for reviewers.
