### ISSUE TITLE
Per-paper COIs and nominated reviewers

### ISSUE THREAD

**Issue by zeeraktalat** [acl-org/aclrollingreview#24]
## Summary

I think that there's a need for identifying reviewers who would have a conflict of interest in reviewing a submission (but whom you don't have a general COI with).
Also, it would make sense to implement structure to nominate reviewers who would be particularly well-suited to review a submission. This is a pretty common interface in a lot of social scientific research venues to help guide reviewer selection.

## Per paper COIs

It can be relevant with per-paper COIs for instance in cases where authors are directly addressing issues with other authors' work or where some specific reviewers would have a vested interest in seeing those papers not be published (disproves, refutes, highlights issues or is competing in time with the would-be COIs work).
This would be on a per-paper basis, it isn't a matter of relationship between authors but between reviewers and submitted paper.

## Per-paper nominated reviewers

This can be useful, particularly for new tasks/methods/theories that are introduced into the ACL community, where it is unclear who a good reviewer is, even to a well informed AE or SAC (if submitted at conference deadline time). In these cases, it could serve as an aid to AEs and SACs in selecting reviewers if some reviewers are already nominated, as AEs and SACs can select reviewers whose body of work/profile is similar to that of the nominated reviewers, if the nominated reviewers aren't available or there's a COI.

**Comment by ajstent** [comment]
agreed, but not an issue for the website...

Please refer to https://github.com/neubig/StarACLReviewing/issues/231 where I have moved this
