### ISSUE TITLE
Permanent Unavailability to review

### ISSUE THREAD

**Issue by zeeraktalat** [acl-org/aclrollingreview#28]
Authors should be provided with the option to never be available to review for ARR under specific conditions.
For instance, authors who are not within the NLP field are unlikely to be qualified reviewers for a majority of submitted papers.
To account for such instances, the review unavailability form should include an option to indicate that although one has submitted work to ARR (as a co-author most likely), one is not qualified to review.

The lack of such a possibility creates unnecessary barriers to interdisciplinary work to appear in ACL venues.

Currently, the only possibility to mark yourself as not qualified to review is marking yourself as unavailable far into the future - which subverts the purpose of unavailability form.

**Comment by ajstent** [comment]
How much of an issue do you think this is? We don't add any reviewers who don't have at least some number (3?5?) recentish *ACL papers, so it literally wouldn't happen?

**Comment by ajstent** [comment]
If it's a messaging issue, can you suggest some language?

**Comment by zeeraktalat** [comment]
Sorry just saw this. I think it's a messaging issue. Will have a look at language tomorrow. :)

**Comment by nschneid** [comment]
Any update on this? Maybe somebody who is added as a reviewer but is no longer active in NLP should just email the EiCs to ask to be removed from the pool?

**Comment by jkkummerfeld** [comment]
Yes, the EICs have honoured such requests in the past. I have added a note to this effect in draft updates to the reviewing page.
