### ISSUE TITLE
ARR ACL Reviewer Console missing rating, review, area chair

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#31]
(moved from https://github.com/openreview/openreview/issues/14 )

**Describe the bug**
Rating, Review, and Area Chair are missing in the ACL ARR Reviewer Console overview (see screenshot)

ACL ARR January 2022

**Screenshots**
![s_2022-02-20_19-37-48](https://user-images.githubusercontent.com/11850778/154858488-31b835de-5a89-4cea-b4fd-30b70a88df1e.png)

> [melisabok](https://github.com/melisabok) commented [1 hour ago](https://github.com/openreview/openreview/issues/14#issuecomment-1047131692)
> These fields "rating" and "review" are not requested in ARR review forms. Please contact the ARR organizers, they should be able to show any other fields of the review.

**Comment by habernal** [comment]
Still there in June ARR but the Area Chair field disappeared now

![a_2022-06-29_09-47-11](https://user-images.githubusercontent.com/11850778/176381644-3ca861d7-cd62-4297-b9e8-49c57046b140.png)

**Comment by habernal** [comment]
ACL ARR 2022 October
Empty **Area chair** is back again...
![screenshot](https://user-images.githubusercontent.com/11850778/199029041-bb7cce53-5890-486b-92f7-4bbcd25a8d27.png)

**Comment by jkkummerfeld** [comment]
Closing as I believe this has since been resolved.

If the issue reappears, please contact the tech team.
