### ISSUE TITLE
Reviewer names are revealed to other reviewers

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#32]
(moved from https://github.com/openreview/openreview/issues/15 )

**Describe the bug**
I'm not sure if this is intentional or not, but as as reviewer, I can see other reviewers' names, e.g.:

```
ACL ARR 2022 January PaperXXX Reviewer XXX FirstName SecondName (privately revealed to you)
```

**Expected behavior**
I believe reviewers should stay anonymous among themselves. I don't see any reason for doing otherwise. Maybe double-check with ARR editors.

>  [melisabok](https://github.com/melisabok) commented [2 hours ago](https://github.com/openreview/openreview/issues/15#issuecomment-1047130305)
> It seems the ARR organizers specified this, please check with the ARR organizers.

**Comment by habernal** [comment]
It seems to be "fixed" by now (March 2022 reviews) -- can someone confirm that it was intentionally changed?

**Comment by nschneid** [comment]
Can this be closed?

**Comment by jkkummerfeld** [comment]
This has been resolved.
