### ISSUE TITLE
Unclear whether authors can see discussions between reviewers and AC

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#33]
Reviews will be made accessible to authors after the "review release" date. However, I don't know whether it is true also for any threads (discussions) between reviewers and ACs.

For example, this is the original review (with some group access rights which do not contain authors yet, I guess?)

![s_2022-02-22_13-26-11](https://user-images.githubusercontent.com/11850778/155132920-3ccc51ba-aa79-49cc-93b8-4b6f85311a4f.png)

And here is my answer to the review as AC where I tried to clarify some potential misunderstandings:

![s_2022-02-22_13-28-02](https://user-images.githubusercontent.com/11850778/155133117-0235f604-0396-4a74-a158-bcdd0afd8484.png)

Both have the same access groups now, but will they all be released to the authors? (which would be favorable, as they add more transparency to the decision process)

**Comment by nschneid** [comment]
Apart from comments explicitly listing the authors as recipients, I believe only the reviews and metareview will be shared, not internal discussions. Is this clear now in the interface?

**Comment by jkkummerfeld** [comment]
The interface now shows for every item who the readers are.
