### ISSUE TITLE
Area Chair console does not show AC Recommendation scores

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#34]
See the screenshot. I would expect that "AC Recommendation:" would display the given score (which is called "Overall Assessment" in the meta review), for example

"AC Recommendation: 3" or better "AC Recommendation: 3 (There are major points that may be revised)"

![s_2022-02-23_10-30-42](https://user-images.githubusercontent.com/11850778/155293156-0ff4ec50-6b13-4a52-b554-8b80a6053c20.png)

**Comment by jkkummerfeld** [comment]
This is not yet implemented, but is on our improvement list. I'm closing the issue here since we want to keep these issues focused on the website.
