### ISSUE TITLE
Autho Console shows no rating, average rating, average confidence

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#39]
See the screenshot, should be self-explaining. (ARR January 2022)

![s_2022-02-28_14-20-37](https://user-images.githubusercontent.com/11850778/155990469-341618a1-8ecb-44a0-a82d-233f88cefeab.png)

**Comment by habernal** [comment]
It hasn't been fixed yet, the averages are now just zeroed:

```plain
Average Rating: 0 (Min: , Max: )
Average Confidence: 0 (Min: , Max: ) 
```

(October 2022 ARR)

**Comment by jkkummerfeld** [comment]
This has been fixed.
