### ISSUE TITLE
Editor/Reviewer Reassignment Request is contradictory

### ISSUE THREAD

**Issue by HaritzPuerto** [acl-org/aclrollingreview#42]
Hello,

When resubmitting a paper, we find this:

![image](https://user-images.githubusercontent.com/2658728/158342064-50a98e72-aa5a-46c5-a8cd-b90e988c1509.png)

The title and the subtitle/explanation are contradictory. I assumed that the right interpretation is the long explanation, but I don't know.

Thank you

**Comment by nschneid** [comment]
Do you mean that answering "yes" to reassignment would imply "no" to the explicit question?

**Comment by habernal** [comment]
It's really confusing - after submission, you only see this:

![Snímek obrazovky_2022-07-15_14-45-31](https://user-images.githubusercontent.com/11850778/179225771-946fec40-3011-4137-bbd1-e5b46133b32e.png)

Suggestion:

"Keep the same editor" - Yes
"Keep the same reviewers" - Yes

**Comment by jkkummerfeld** [comment]
These questions and labels have been updated to be consistent and clear.
