### ISSUE TITLE
ARR June 2022: Wrong radio buttons/checkbox on Ethics review

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#53]
ACL ARR June 2022

Role: Reviewer

Bug: Ethics review Yes/No -> Radio button only for Yes (but No missing), see below

Fix: Either checkbox or radio buttons Yes + No

![Snímek obrazovky_2022-06-29_09-43-49](https://user-images.githubusercontent.com/11850778/176380721-b0fce7d5-a1ef-49fe-baa9-7042c59bbda7.png)

**Comment by jkkummerfeld** [comment]
This has been resolved.
