### ISSUE TITLE
ARR Feb 2023: Reviewers from previous round leaking to current (?)

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#76]
I'm AE for Feb 2023 ARR, and for some papers I can see previous reviewers (?) with some wierd IDs (NaN etc.)... When opening detail page of the paper, there's no reviews visible.

![arr_2023-02-23_11-04-13](https://user-images.githubusercontent.com/11850778/220877188-a7b4fd05-0a32-44b6-abb0-3b78d92cb5e4.png)

**Comment by jkkummerfeld** [comment]
Hi,
Thanks for raising this. Please note that this issue tracker is for the ARR website. For technical issues with Open Review, please contact the tech team directly.

I'll follow up via email and look into getting this resolved.

Jonathan
