### ISSUE TITLE
ARR AC June 2023: "Show reviewers" doesn't work

### ISSUE THREAD

**Issue by habernal** [acl-org/aclrollingreview#83]
June 2023, AC-ing
![step1](https://github.com/acl-org/aclrollingreview/assets/11850778/fa67e850-8250-46d8-8b99-a5e325c98a56)
after clicking on "Show reviewers", it shows an input box instead of a list of reviewers (?)
![step2](https://github.com/acl-org/aclrollingreview/assets/11850778/ae443abe-9591-43a0-83dd-20560902c829)

**Comment by nschneid** [comment]
Higher on the page it says:

> Reviewer assignments will not show up in the Assigned Papers tab while they are not deployed. To modify your assignments or view them before they are deployed, use the link below:

I assume this means the reviewer assignments have not been sent out yet.

**Comment by habernal** [comment]
Oh, OK, that's why (maybe?)

The ARR schedule said

> June 28th to July 20th: Reviewing period

though, and as far as I know ACs are not notified that the reviewing has started.

**Comment by jkkummerfeld** [comment]
Reviewing for June has not started yet, I believe there are some outstanding AE checklists (the forms that confirm the assignments are good).

The idea of displaying the schedule is good. I'll add it to our list of ideas.

Note - in future, please email the tech team directly with this type of question. This repository's issue page is intended to be for website issues only. It is on our todo list to modify the issue creation setup to say that when someone goes to create an issue.

**Comment by jkkummerfeld** [comment]
Reviewing for June has not started yet, I believe there are some outstanding AE checklists (the forms that confirm the assignments are good).

The idea of displaying the schedule is good. I'll add it to our list of ideas.

Note - in future, please email the tech team directly with this type of question. This repository's issue page is intended to be for website issues only. It is on our todo list to modify the issue creation setup to say that when someone goes to create an issue.
