### ISSUE TITLE
Add a login button  or link

### ISSUE THREAD

**Issue by thammegowda** [acl-org/aclrollingreview#99]
**Is your feature request related to a problem? Please describe.**
Is there a login link on the home page? I cant find it. It's frustrating to find where to login for reviewing. Adding a Login link at *the top would be helpful. 
![image](https://github.com/acl-org/aclrollingreview/assets/1865964/4c559322-bbaa-4090-9a74-b12c0ef2640b)

**Describe alternatives you've considered**
Alternative is to memorize that I need to login to Openreview.net not aclrollingreview.org

**Comment by jkkummerfeld** [comment]
Thanks for the suggestion! I've implemented this.

The link goes to the list of ARR cycles in OpenReview. Going to the current cycle might be more convenient, but would also require updating every cycle.

**Comment by thammegowda** [comment]
That was super quick! Thank you.
